apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "fluentbit.fullname" . }}
  labels:
    {{- include "fluentbit.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "fluentbit.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fluentbit.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "fluentbit.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: fluent-bit
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: ELASTICSEARCH_HOST
          value: {{ .Values.elasticsearch.host | quote }}
        - name: ELASTICSEARCH_PORT
          value: {{ .Values.elasticsearch.port | quote }}
        - name: ELASTICSEARCH_INDEX
          value: {{ .Values.elasticsearch.index | quote }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc
        - name: fluent-bit-state
          mountPath: /var/fluent-bit/state
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluent-bit-config
        configMap:
          name: {{ include "fluentbit.fullname" . }}-config
      - name: fluent-bit-state
        hostPath:
          path: /var/fluent-bit/state
          type: DirectoryOrCreate
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

