{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "fluentbit.fullname" . }}
  labels:
    {{- include "fluentbit.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "fluentbit.fullname" . }}
  labels:
    {{- include "fluentbit.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "fluentbit.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "fluentbit.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}

